### ISSUE TITLE
Helper plugin + user-bound data

### ISSUE THREAD

**Issue by DragOncave** [wilminator/dokuwiki-plugin-twofactor#6] opened 2016-06-10 16:25 UTC
Hi, I'm trying to set up the plugin wit Google auth for our wiki, but all I keep getting is:

Helper plugin attribute is not available or invalid.
Helper plugin attribute is not available or invalid.
You do not have the twofactor plugin configured to store user-bound data, so there is nothing to administer.

I tried it even with Email helper plugin, but still the same and I can't figure out what's wrong

![2](https://cloud.githubusercontent.com/assets/1708383/15971278/a31a271c-2f38-11e6-9255-015ab48da0de.png)
![1](https://cloud.githubusercontent.com/assets/1708383/15971277/a318de48-2f38-11e6-85d6-2d44c066aa62.png)

**Comment by litewhatever** [comment] 2016-10-29 14:15
Same issue here. Did you ever resolve it?
Perhaps dev can give some advice? Should this plugin work with latet version.

**Comment by PaulRotter** [comment] 2016-11-03 11:05
The second message is caused by the [admin page not finding users with twofactor auth](https://github.com/wilminator/dokuwiki-plugin-twofactor/blob/master/admin.php#L76). This is because none of them have the appropriate attribute set. The reason for that is the first error message - being that attributes cannot be set because the needed plugin is missing. The error message is somewhat confusing, but [digging in dokuwiki code](https://github.com/splitbrain/dokuwiki/blob/master/inc/plugin.php#L228) reveals that indeed not an attribute of a plugin is missing but a plugin named "attribute".
You can [find the attribute module here](https://www.dokuwiki.org/plugin:attribute). Installation of that solved it for me.

**Comment by ThiloE** [comment] 2017-03-03 04:13
Thank you so much @PaulRotter! I was experiencing the same issue and would have never come to the conclusion that a plugin called "attribute" was meant by the error message.

**Comment by wilminator** [comment] 2017-03-03 05:22
My apologies- I didn't see this thread last year.  I will update the error message to be more clear and specific about what is being asked.

**Comment by wilminator** [comment] 2017-03-09 06:18
I have committed an update that hopefully is more clear about the need for the Attribute plugin.  I'm closing this issue, but welcome feedback about how well the new messages work.

**Closed by wilminator** 2017-03-09 06:18 UTC
