### ISSUE TITLE
Message "plugin depends on the Attribute helper plugin being installed" when 2F is disabled

### ISSUE THREAD

**Issue by ChrisLambertUK** [wilminator/dokuwiki-plugin-twofactor#8] opened 2017-07-29 06:50 UTC
When first installed in Dokuwiki the TwoFactor plugin is not enabled by default.
On the Admin page this message appears "The TwoFactor plugin depends on the Attribute helper plugin being installed. Without the Attrubute plugin, TwoFactor cannot store data and will not function"
But installing Attribute (note the spelling!) doesn't make the above message go away.
However enabling TwoFactor in Configuration does make the message go away.
Could the message be suppressed when TwoFactor is not enabled?

**Comment by wilminator** [comment] 2018-06-20 06:33
I think I supplied a fix for this last year.  With the current codebase I released today, I cannot replicate this issue.  If it is still a problem, please re-open this issue and we can work through it.

**Comment by wilminator** [comment] 2018-06-20 06:35
Wait, just got it.  I'm looking into this.

**Comment by wilminator** [comment] 2018-06-20 06:44
I found the cause of the message and fixed it.  Please confirm that you no longer have this issue.

**Comment by wilminator** [comment] 2018-07-20 02:34
Closing due to age.

**Closed** 2018-07-20 02:34 UTC
